### ISSUE TITLE
Exception if function does not exist

### ISSUE THREAD

**Issue by movAX13h** [frabert/NetLua#6]
https://github.com/frabert/NetLua/blob/master/NetLua/LuaEvents.cs#L290
causes an (null reference) exception (not LuaException) when Lua tries to call a function that does not exist.

To reproduce, simply call a nonexisting function:
lua.DoString("anything()");

I don't exactly understand which part of it is null. Would be nice to get the name and line number of the missing function in a (Lua)Exception message.

**Comment by frabert** [comment]
This should have solved it. As for the line numbers, it is surely a big issue, but not one that can be solved in a short time... Will look into that, though.

**Comment by movAX13h** [comment]
That was fast, thanks a lot!
