### ISSUE TITLE
Would there be an easy way to go through the AST.

### ISSUE THREAD

**Issue by GoddHoward** [frabert/NetLua#7]
Curious to see so I can output everything in the AST.

**Comment by frabert** [comment]
Hi! What exactly do you mean by outputting in the AST? Do you want to create your own frontend which then gets executed on the NetLua interpreter?

Also, please note that I have not been developing this for a long time, this project was pretty much an exercise in learning what _not_ to do for me, so I don't intend to add major features to it, also the VM's speed is quite low. I will try fixing bugs, though

**Comment by GoddHoward** [comment]
Like for example, the AST or, the Block class, is a class that holds a bunch of list's of interface's and classes.

Would there be a way to output everything in just one big string, with Console.WriteLine. Or would i have to go through every List, manually?

**Comment by frabert** [comment]
Ah - maybe I understand now... You want to make something like a pretty-printer? The easiest way in that case would be to implement a Visitor pattern for each `IStatement` and `IExpression`. Or you could override the `ToString` method to recursively output the generated string, something like this:

````
public class WhileStat : IStatement
{
        public IExpression Condition;
        public Block Block;
        public override string ToString() {
            return $"while {Condition.ToString()} do\n{Block.ToString()}\nend";
        }
}
````

**Comment by GoddHoward** [comment]
Exactly what I was looking for thanks!

**Comment by frabert** [comment]
Closing the issue... Post again if you have further questions!
